export const movieActionTypes = {
  FETCH_ALL_MOVIE: "FETCH_ALL_MOVIE",
  SET_ALL_MOVIE: "SET_ALL_MOVIE",
  SET_POPULAR_MOVIE: "SET_POPULAR_MOVIE",
  SET_NOW_MOVIE: "SET_NOW_MOVIE",
  SET_SEARCHED_MOVIES: "SET_SEARCHED_MOVIES",
};
